server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO:}
      database: ${DATABASE:dnser}

cloudflare:
  url: https://api.cloudflare.com/client/v4/
  zone: ${CLOUDFLARE_ZONE:}
  token: ${CLOUDFLARE_TOKEN:}