server:
  port: ${port:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO:}
      database: ${database:dnser-test}

cloudflare:
  url: https://api.cloudflare.com/client/v4/
  zone: ${ZONE:}
  token: ${TOKEN:}